### ISSUE TITLE
Rackspace configuration problem? 

### ISSUE THREAD

**Issue by skylord123** [KnpLabs/KnpGaufretteBundle#106]
Okay.. It's end of Friday and this is driving me nuts. Maybe someone here can help.

I added this to my app/config/config.yml
```
knp_gaufrette:
    adapters:
        website_resources:
            opencloud:
                object_store_id: opencloud.object_store
                container_name: hidden_container
    filesystems:
        rackspace:
            adapter:    website_resources
            alias:      rackspace_filesystem
services:
    opencloud.connection.rackspace:
        class: OpenCloud\Rackspace
        arguments:
          - 'https://identity.api.rackspacecloud.com/v2.0/'
          - {username: %rackspace.username%, apiKey: %rackspace.api_key%}

    opencloud.object_store:
        class: OpenCloud\ObjectStoreBase
        factory_service: opencloud.connection.rackspace
        factory_method: ObjectStore
        arguments:
          - 'cloudFiles' # Object storage type
          - 'IAD' # Object storage region
          - 'publicURL' # url type
```

and everytime I try to run `$this->get('knp_gaufrette.filesystem_map')` I get the following:

```
Attempted to call method "ObjectStore" on class "OpenCloud\Rackspace".
500 Internal Server Error - UndefinedMethodException
```

I know it's somewhere in my configuration bui I have no clue where.

Basically I just want to store all the assets for this server on Rackspace.

Any help is GREATLY appreciated!
