### ISSUE TITLE
 Retrieve a secure file using AWS

### ISSUE THREAD

**Issue by thmohd** [KnpLabs/KnpGaufretteBundle#111]
I am using KnpGaufretteBundle with Vich uploader, everything work well, I upload to AWS but my files are secured on AWS and I don't want them be public, How can I retrieve a file using AWS key and secret key same way I used them for uploading, I want create Download link inside twig file but be served from my application which require authenticated user 

My config file is ::
```yaml
services:
      amazonS3:
          class: AmazonS3
          arguments:
              options:
                  key:      '%aws_key%'
                  secret:   '%aws_secret_key%'




knp_gaufrette:
    stream_wrapper: ~

    adapters:
        zip_uploads:
            amazon_s3:
                amazon_s3_id:   amazonS3
                bucket_name:    my_bucket

    filesystems:
            amazon_s3:
                adapter:    zip_uploads

vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
           zip_file:
                   uri_prefix:         https://s3.amazonaws.com/my_bucket
                   upload_destination: amazon_s3
                   namer:              vich_uploader.namer_uniqid
                   inject_on_load:     true
                   delete_on_update:   true
                   delete_on_remove:   true
```
