### ISSUE TITLE
Dropbox client

### ISSUE THREAD

**Issue by dafuer** [KnpLabs/KnpGaufretteBundle#120]
Hi all,

   I have problems to follow the procedure to set up a dropbox client. Could someone help me?  The documentation is little bit difficult to follow... It says:
```
services:
    acme_test.dropbox.oauth:
        class: Dropbox_OAuth_Curl
        arguments: [%acme_test.dropbox.key%, %acme_test.dropbox.secret%]
        calls:
            - [setToken, ["%acme_test.dropbox.token%", "%acme_test.dropbox.token_secret%"]]
    acme_test.dropbox.api:
        class: Dropbox_API
        arguments: [@acme_test.dropbox.oauth, "sandbox"]
```

What classes should I use like Dropbox_OAuth_Curl and Dropbox_API. 

Thanks.
