### ISSUE TITLE
Can't connect to S3 anymore

### ISSUE THREAD

**Issue by Ezor** [KnpLabs/KnpGaufretteBundle#136]
Hi,

I'm getting the following error while trying to connect to a S3 bucket :
`Catchable Fatal Error: Argument 1 passed to Aws\\Common\\Client\\AbstractClient::__construct() must be an instance of Aws\\Common\\Credentials\\CredentialsInterface, array given`

Here is my service declaration 

```
acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: "%amazon_s3.key%"
                secret: "%amazon_s3.secret%"
                region: "%amazon_s3.region%"
```

My composer.son :

```
"knplabs/gaufrette":                    "~0.2",
        "knplabs/knp-gaufrette-bundle":         "~0.3",
        "aws/aws-sdk-php": "2.*"
```
