### ISSUE TITLE
Setting up AWS

### ISSUE THREAD

**Issue by danwoodbury** [KnpLabs/KnpGaufretteBundle#137]
I cant seem to use the S3 client. After following the docs in the readme for AwsS3 I get an nasty type error which makes sense but cannot work out the correct setup.

> Type error: Argument 1 passed to Gaufrette\Adapter\AmazonS3::__construct() must be an instance of AmazonS3, instance of Aws\S3\S3Client given

This is my composer setup: 

> "knplabs/gaufrette": "~0.2",
        "knplabs/knp-gaufrette-bundle": "~0.3",
        "aws/aws-sdk-php": "3.15.*"

My services:

    admin.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                credentials:
                    key: %amazon_aws_key%
                    secret: %amazon_aws_secret_key%
                region: %amazon_s3_region%
                version: %amazon_s3_version%
    
    admin.image_service:
        class: AdminBundle\Service\ImageService
        arguments: ["@service_container", "@doctrine.orm.admin_entity_manager", "@image_storage_filesystem"]

Gaufrette setup:

    knp_gaufrette:
    adapters:
        image_storage:
            amazon_s3:
                amazon_s3_id: admin.amazon_s3
                bucket_name:  %amazon_s3_bucket_name%
                options:
                    directory: 'test'
    filesystems:
        image_storage:
            adapter:    image_storage
            alias:      image_storage_filesystem

Any pointers in the right direction would be much appreciated.
Thanks

**Comment by akovalyov** [comment]
@danwoodbury your exception stack trace tells you the truth. It expects `AmazonS3`, but you have configured `S3Client`. Please, check out https://github.com/KnpLabs/KnpGaufretteBundle#defining-services. 
BTW, just a small note - please, don't inject `service_container

**Comment by danwoodbury** [comment]
Ok thanks for the advice.

I looked at the docs you pointed to and it says to use amazonwebservices/aws-sdk-for-php which is deprecated. How can I set this up to use a newer version of aws/aws-sdk-php? From what I understood, they way I am trying to set it up should be correct for a newer version of the sdk?

**Comment by akovalyov** [comment]
@danwoodbury well, you can use https://github.com/KnpLabs/KnpGaufretteBundle#awss3 then. I suggest you to install https://github.com/aws/aws-sdk-php-symfony, configure it as it described in readme there and then setup your gaufrette services according to readme. 

```yaml
knp_gaufrette:
    adapters:
        image_storage:
            aws_s3:
                service_id: `aws.s3`
                bucket_name:  %amazon_s3_bucket_name%
                options:
                    directory: 'test'
    filesystems:
        image_storage:
            adapter:    image_storage
            alias:      image_storage_filesystem
```

It is something we should add to readme as the most straightforward way /cc @NiR-
