### ISSUE TITLE
Test with PhpSpec, wrapper not found

### ISSUE THREAD

**Issue by guillaumedev** [KnpLabs/KnpGaufretteBundle#140]
Hi,

When i use PhpSpec to test a method that uses a fopen with a wrapper (fopen('sw://files/')), i have an error message when i run my spec : 

> warning: file_put_contents(): Unable to find the wrapper "sw" - did you forget to enable it when you configured PHP? 

In my config file I have this : 

```
knp_gaufrette:
    adapters:
        files_adapter:
            local:
                directory: /var/files
    filesystems:
        files:
            adapter: files_adapter
    stream_wrapper:
        protocol: sw
        filesystems:
            - files
```

If I retrieve all wrappers with stream_get_wrappers(), there is no sw wrapper.

Do you have any idea why this occurs ? I can provide you more information if needed. 

BTW, sorry for bad English ! 

Thank you !
