### ISSUE TITLE
Is Openstack (OVH object storage bucket) supported by this bundle? 

### ISSUE THREAD

**Issue by glederer** [KnpLabs/KnpGaufretteBundle#142]
does this bundle actually support openstack? After a few hours of trying to get a working configuration, I admit this seems to be not so sure.

The end of the readme (here exactly : https://github.com/KnpLabs/KnpGaufretteBundle#open-cloud-opencloud) explains a opencloud/rackspace approach or opencloud/hpcloud approach. But it is unclear about a opencloud/openstack use case. There is no explanation to define the needed service for this use case. I did not totally understand the specific paragraph : 

>   To use the OpenCloud adapter you should provide a valid ObjectStore instance. You can retrieve an instance through the OpenCloud\OpenStack or OpenCloud\Rackspace instances. We can provide a comprehensive configuration through the Symfony DIC configuration." But only hpcloud and rackspace examples are given just after.

I wish I could use Gaufrette Bundle on an OVH Object storage (Openstack) bucket, but googling a few hours now, I have seen no-one do that so far. Is it actually possible?

Thank you for reading, any help appreciated. I'd be glad to improve the doc if I manage to make it work.

**Comment by glederer** [comment]
here is a gist to explain what I tried, any help appreciated.

https://gist.github.com/glederer/546b7491bddc4061b46ff4282ddcdaf1

**Comment by nicolasmure** [comment]
Hello @glederer ,

Sorry for the late answer, here's the config I've tested with openstack identity v2 (on rackspace, but as it is what OVH seems to use, it should be fine too in your case) : 

```yaml
# app/config/config.yml
knp_gaufrette:
    adapters:
        object_storage:
            opencloud:
                object_store_id: opencloud.object_store
                container_name: debug
                create_container: true
                detect_content_type: true
    filesystems:
        test_object_storage:
            adapter: object_storage
```
```yaml
# app/config/services.yml
services:
    opencloud.connection:
        class: OpenCloud\OpenStack
        arguments:
            - https://identity.api.rackspacecloud.com/v2.0/
            - {username: 'j.doe', password: 'p4ssw0rd', tenantId: '12345678'}

    opencloud.object_store:
        class: OpenCloud\ObjectStore\Service
        arguments:
            - '@opencloud.connection'
            - 'object-store'
            - 'cloudFiles'
            - 'LON'
            - 'publicURL'
```

```php
// src/AppBundle/Controller/DefaultController.php
namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/test-gaufrette", name="test_gaufrette")
     */
    public function testGaufretteAction(Request $request)
    {
        $fs = $this->get('gaufrette.test_object_storage_filesystem');

        return $this->render('@AppBundle/default/test-gaufrette.html.twig', [
            'keys' => $fs->keys(),
        ]);
    }
}
```
