### ISSUE TITLE
Error retrieving credentials from the instance profile metadata server. 

### ISSUE THREAD

**Issue by janjango** [KnpLabs/KnpGaufretteBundle#143]
Hello,
I get **Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1045 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))** while configuring **aws s3 with GaufretteBundle in Symfony3**
Here is my config:
```    
services
    aws.s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            - 
                key:    %aws.key%
                secret: %aws.secret%
                region: %aws.region%
                version: "2006-03-01" 
```
I think that the new configuration should be in the following form (http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#credentials):
```
$s3 = new Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'us-west-2',
    'credentials' => [
        'key'    => 'abc',
        'secret' => '123'
    ]
]);
```
So I tried:

```
services
    aws.s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            - 
                version: "2006-03-01"
                region: %aws.region%
                credentials: [%aws.key%, %aws.secret%]
```
And get this error:
`Credentials must be an instance of Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false.`

Any help please ?

**Comment by mickaelvalmier** [comment]
Hi,

Credentials need an associative array that contains key and secret fields, try this : 
```
services
    aws.s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            - 
                version: "2006-03-01"
                region: %aws.region%
                credentials: ['key' => %aws.key%, 'secret' => %aws.secret%]
```

**Comment by nicolasheraly** [comment]
@mickaelvalmier thanks, you saved my day.

Just a little thing to fix in your example:

         credentials: ['key' : '%aws.key%', 'secret': '%aws.secret%']

**Comment by mickaelvalmier** [comment]
Hi,

I have fixed my example. Thanks!

**Comment by NiR-** [comment]
It has been fixed. Thank your for reporting it :)

**Comment by nietzscheson** [comment]
@mickaelvalmier's response continued to give me the same error. This works for me:

```yml
services
    aws.s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            - 
                version: "2006-03-01"
                region: %aws.region%
                #credentials: ['key' : %aws.key%, 'secret' : %aws.secret%]
                credentials: {'key' : %aws.key%, 'secret' : %aws.secret%}
```
