### ISSUE TITLE
Google Cloud Storage Authentification

### ISSUE THREAD

**Issue by yoruyer** [KnpLabs/KnpGaufretteBundle#145]
Hi everyone,
I try to configure KnpGaufretteBundle for Google Cloud Storage. I made my adapter, and when i try, to read/write or delete a file, I throw an Exception.
If someone can help me..
Thanks.

Here is my adapter : 

```
public function createService($googleCloudStorageIdKey, $googleCloudStorageKey, $googleCloudStorageSecret)
    {
        //Creating new Google Client
        $client = new \Google_Client();

        //Setting the service account credentials
       $scopes = array(\Google_Service_Storage::DEVSTORAGE_FULL_CONTROL);
       $cred = new Google_Auth_AssertionCredentials($googleCloudStorageIdKey,
                                                    $scopes,
                                                    file_get_contents($googleCloudStorageKey),
                                                    $googleCloudStorageSecret);
        $client->setAssertionCredentials($cred);
        if ($client->getAuth()->isAccessTokenExpired()) {
            $client->getAuth()->refreshTokenWithAssertion($cred);
        }
        $service = new\Google_Service_Storage($client);
        return ($service);
}
```

In a other file i made this : 

 ```
public function readFile()
    {
        $service = $this->get('knp_gaufrette.filesystem_map')->get('billing_gcs_fs');
        $service->read('Task.java');
        return;
    }
```

That code return this error : 

> The configured bucket "my_bucket" does not exist.
> File gaufrette\src\Gaufrette\Adapter\GoogleCloudStorage.php at Line=342

If i delete the try/catch at Line 342, i throw this error : 

> Error calling GET https://www.googleapis.com/storage/v1/b/my_bucket: (403) Caller does not have storage.buckets.get access to bucket my_bucket.
> File vendor\google\apiclient\src\Google\Http\REST.php at Line=110

Of course, i remplaced my_bucket by the real name of my bucket. And I create the bucket via google console cloud api.
I think my configuration in config.yml is right : 

```
#config.yml
knp_gaufrette:
    stream_wrapper: ~
    adapters:
            billing_gcs:
                    google_cloud_storage:
                        service_id: 'app.google_cloud_storage.service'
                        bucket_name: 'my_bucket'
                        options:
                           directory: 'billing'
   filesystems:
         billing_gcs_fs:
            adapter:    billing_gcs
```

and : 

```
# definition of the GoogleCloudStorageService
    app.google_cloud_storage.service:
        class: \Google_Service_Storage
        factory: [my_path\to\my_file\GoogleCloudStorage\GoogleCloudStorageFactory, 'createService']
        arguments:
            - "%google_cloud_storage_id_key%"  #like something.iam.gserviceaccount.com
            - "%google_cloud_storage_key%"      #path to my p12 file
            - "%google_cloud_storage_secret%" #like noasecret
```
