### ISSUE TITLE
ec2 role as auth credentials

### ISSUE THREAD

**Issue by davrodfer** [KnpLabs/KnpGaufretteBundle#156]
How to use ec2 role as authentication credentials? Is it possible with this library?

**Comment by NiR-** [comment]
Fortunately we wrote [a little article about that](http://knplabs.com/en/blog/how2tips-call-aws-apis-from-ec2-instances-with-no-credentials) on our blog some weeks ago :) The proposed solution is generic and should work for any AWS API client. Note that I tested it using version 3 of the SDK and I don't know if it works with version 2.

```php
<?php

use Aws\Credentials\InstanceProfileProvider;
use Aws\S3\S3Client;
use Gaufrette\Adapter\AwsS3 as AwsS3Adapter;
use Gaufrette\Filesystem;

// For aws-sdk-php v3
$s3client = new S3Client([
    'credentials' => new InstanceProfileProvider(),
    'version' => 'latest',
    'region'  => 'eu-west-1',
]);

$adapter = new AwsS3Adapter($s3client,'your-bucket-name');
$filesystem = new Filesystem($adapter);
```

**Comment by davrodfer** [comment]
I'll try!
Thank you very much !

**Comment by NiR-** [comment]
Could you tell me if it works properly? I would like to add a little note about that in the doc.

**Comment by davrodfer** [comment]
When I can make sure it's working, I'll update the thread.
Thanks.

**Comment by NiR-** [comment]
Any news? :)

**Comment by damienthiesson** [comment]
This is not really a KnpGaufrette issue, as the S3Client is injected as a service in the adapter.

Tried on my side, it works out of the box: if you omit the credentials, S3Client will look for the IAM role.

Working example:
```
# app/config/config.yml
knp_gaufrette:
    adapters:
        acme:
            aws_s3:
                service_id: 'acme.aws_s3.client'
                bucket_name: '%aws_bucket_name%'
                detect_content_type: true
    filesystems:
        abms:
            adapter:    acme
            alias:      acme_filesystem

services:
    acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: latest
                region: ap-southeast-2
```

To use the service:
```php
/**
     * @Route("/list-files", options={"expose"=true})
     */
    public function listFilesAction() {
        $filesystem = $this->container->get('knp_gaufrette.filesystem_map')->get('acme');
        return new JsonResponse($filesystem->listKeys());
    }
```
