### ISSUE TITLE
ResolvableFilesystem

### ISSUE THREAD

**Issue by snake77se** [KnpLabs/KnpGaufretteBundle#166]
What is the correct way to use the "ResolvableFilesystem" of "Gaufrette/Extra" in KnpGaufretteBundle?.
Think about adding a service like FileSystem and so the configuration will take, but the configuration of the filesytems does not accept services, only the adapters.

``` yaml
# app/config/config.yml
knp_gaufrette:
    adapters:
        # ...
    filesystems:
        bar:
            service:    my_service_resolvable_filesystem
            alias:      foo_filesystem
```

Thanks.

**Comment by 7thcubic** [comment]
Currently the bundle isn't on 0.4 Gaufrette, which means no Gaufrette\Extra because extra requires the FilesystemInterface which isnt available on 0.3

**Comment by fabianoroberto** [comment]
Is anyone working on this issue?

**Comment by 7thcubic** [comment]
Actually i think 0.4 does not have any conflict with 0.3. You can simply bump the composer

Simply use the following in composer

```yaml
    "knplabs/gaufrette": "~0.4",
    "gaufrette/extras": "~0.1",
    "knplabs/knp-gaufrette-bundle": "^0.4.0",
```

Note. if you are using sonata media bundle it wont work unless you ignore requirement.
Apparently their bundle does not support 0.4 gaufrette, they need to bump it up
