### ISSUE TITLE
Adapter is not defined

### ISSUE THREAD

**Issue by konradja100** [KnpLabs/KnpGaufretteBundle#213]
Hi, we're using this bundle with SF 2.4.5, for for S3 storage. We have one filesystem called invoice with only one adapter - also called invoice. For local enviroment we use local storage with this configuration:

```
knp_gaufrette:
    adapters:
        invoice:
            local:
                directory: '%env(GAUFRETTE_LOCAL_DIRECTORY)%'
```

And for production:

```
knp_gaufrette:
    adapters:
        invoice:
            aws_s3:
                service_id: 'invoice.aws_s3.client'
                bucket_name: '%env(GAUFRETTE_AMAZONS3_BUCKET)%'
                detect_content_type: true
                options:
                    directory: '%env(GAUFRETTE_AMAZONS3_DIRECTORY)%'
```

So the issue appears today, as we call command not even related to this budle - we just wanna send some email reports.  

Error:
![image](https://user-images.githubusercontent.com/28842587/55724962-d455a200-5a0c-11e9-9e49-e5416d60d32a.png)

Week ago everything was working fine, no deployments since that day, no other errors, no data corruption, event cache was not cleared. Has anyone struggled with such situation?
