### ISSUE TITLE
Problems when integrate the S3 on project Symfony 5.1

### ISSUE THREAD

**Issue by andreguipeil** [KnpLabs/KnpGaufretteBundle#239]
Hello!
I receive a error when I was integrating the Gaufrette with S3 adapter, the error is:

You have requested a non-existent parameter "knp_gaufrette.stream_wrapper.protocol".

My config is:
```
knp_gaufrette:
  adapters:
    cavb_images_adapter:
      aws_s3:
        service_id: 'acme.aws_s3.client'
        bucket_name: ''%env(AWS_BUCKET)%''
        detect_content_type: true
  stream_wrapper: ~
  filesystems:
    cavb_images_fs:
      adapter: cavb_images_adapter

```

I'm installed VichImage and php-sdk to adapt to S3 but I receive this error and I don't know what I need to do.

My symfony version is: 5.1
