### ISSUE TITLE
ResolverInterface gaufrette-extra

### ISSUE THREAD

**Issue by TomAMarine** [KnpLabs/KnpGaufretteBundle#249]
Hello,

I have this configuration bundle : 

```yaml
knp_gaufrette:
    stream_wrapper: ~

    adapters:
        data_library_model_image:
            aws_s3:
                service_id: 'aws_s3.client'
                bucket_name: '%aws_s3.bucket%'
                detect_content_type: true
                options:
                    directory: 'data-library/model'
                    acl: 'public-read'

    filesystems:
        data_library_model_image:
            adapter: data_library_model_image
```

I use Gaufrette which provides me with an alias / service: "gaufrette.data_library_model_image_filesystem". 
I would like to replace or override it to implement the "ResolvableFilesystem" (see bundle [gaufrette/extra](https://github.com/Gaufrette/extras)).

How can I get the Filesystem decorator (ResolverInterface) with the "knp_gaufrette.filesystem_map" system?
