### ISSUE TITLE
Unable to find the wrapper "gaufrette"

### ISSUE THREAD

**Issue by Chrysweel** [KnpLabs/KnpGaufretteBundle#25]
Hello.

I have a problem. I get the following error when I want edit my email with FOSUSerBundle.

```
Warning: is_file(): Unable to find the wrapper "gaufrette" - did you forget to enable it when you configured PHP? in /var/www/workspace/chateagratis/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/FileValidator.php line 85 
```

My config.yml is:

```
knp_gaufrette:
    adapters:
        product_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/fotos
        perfil_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/perfil

    filesystems:
        product_image_fs:
            adapter:    product_adapter
        imagen_perfil_fs:
            adapter:    perfil_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        product_image:
            uri_prefix: /workspace/myproject/web/uploads/perfil
            upload_destination: product_image_fs
        imagen_perfil:
            uri_prefix: /workspace/myproject/web/uploads/perfil
            upload_destination: imagen_perfil_fs  
```

Any idea? Thanks!!
