### ISSUE TITLE
Dropbox adapter : Configuration

### ISSUE THREAD

**Issue by fdiedler** [KnpLabs/KnpGaufretteBundle#261]
Hi,

I try to configurate Gaufrette with Dropbox adapter. I added the configuration 
```
acme_test.dropbox.oauth:
        class: Dropbox_OAuth_Curl
        arguments: ["%acme_test.dropbox.key%", "%acme_test.dropbox.secret%"]
        calls:
            - [setToken, ["%acme_test.dropbox.token%", "%acme_test.dropbox.token_secret%"]]
    acme_test.dropbox.api:
        class: Dropbox_API
        arguments: ["@acme_test.dropbox.oauth", "sandbox"]
```

But where can I find the token_secret parameter ? I have only the dropbox_key, dropbox_secret and dropbox_token on my dropbox account...

Thanks
