### ISSUE TITLE
How to configure ACL aware Amazon S3?

### ISSUE THREAD

**Issue by gavD** [KnpLabs/KnpGaufretteBundle#40]
Hi,

I am using Symfony2 with "knplabs/knp-gaufrette-bundle" : "0.1.4" and need to configure ACL aware S3

I have tried:

```
knp_gaufrette:
  adapters:
    amazon_adapter:
        acl_aware_amazon_s3:
            amazon_s3_id: storage.s3
            bucket_name: %storage.s3.bucket_name%
            create: true
            options:
                region: %storage.s3.region%
```

I got:

  InvalidConfigurationException: Unrecognized options "options" under "knp_gaufrette.adapters.amazon_adapter.acl_aware_amazon_s3"

I removed the options and tried:

```
knp_gaufrette:
  adapters:
    amazon_adapter:
        acl_aware_amazon_s3:
            amazon_s3_id: storage.s3
            bucket_name: %storage.s3.bucket_name%
            create: true
```

I got:

```
ErrorException: Warning: array_replace_recursive(): Argument #2 is not an array in /opt/BoxUK/swb/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/AmazonS3.php line 31
```

This appears to correspond to options not being set.

I can't find any examples of configuring this anywhere online, please could somebody help me out?

Thanks,
- Gavin
