### ISSUE TITLE
S3 StreamWrapper issue with Directories

### ISSUE THREAD

**Issue by jdelaune** [KnpLabs/KnpGaufretteBundle#43]
So I've setup my S3 StreamWrapper

```
knp_gaufrette:
    adapters:
        amazon:
            amazon_s3:
                amazon_s3_id: aws_s3
                bucket_name: %aws_bucket%
                create: true
                options:
                    region: %aws_region%

    filesystems:
        amazon:
            adapter: amazon

    stream_wrapper:
        protocol: data
        filesystems:
            s3: amazon
```

I'm trying to move an uploaded file to s3: `$this->file->move($this->getUploadRootDir(), $this->id . '.' . $this->extension);` where `$this->getUploadRootDir()` resolves to `data://s3/pictures/profiles`

However in the move function it looks to see if `$directory` is an actual directory and tries to create it which seems to trick the stream wrapper a bit. Have I done something wrong? I thought the stream wrapper should be able to overcome these sort of issues?

Thanks
