### ISSUE TITLE
stream writer can't write folders to S3

### ISSUE THREAD

**Issue by echoedexistence** [KnpLabs/KnpGaufretteBundle#47]
I have the following config:

```
knp_gaufrette:
    adapters:
        amazon:
            amazon_s3: 
                amazon_s3_id: site_store.s3
                bucket_name: %site_store.bucket_name%
                create: true

filesystems:
    amazon:
        adapter: amazon

stream_wrapper:
    protocol: s3
    filesystems:
        - amazon

assetic:
    read_from:      %cdn_path_prod%
    write_to:       %cdn_path_prod%
```

however when I try to dump all of the assets it always gives me:

```
[RuntimeException]                          
  Unable to create directory s3://amazon/css  
```

I've looked at the following thread (https://github.com/Cybernox/AmazonWebServicesBundle) and it says to return true in the mkdir function, I did that however it's still erroring. Any idea?

**Comment by bassrock** [comment]
This works somewhat if you switch to aws sdk 3.0 and change the aws initialization like so:

```
    aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                credentials:
                    key: %amazon_aws_key%
                    secret: %amazon_aws_secret_key%
                region: 'us-east-1'
                version: 'latest'
```
