### ISSUE TITLE
bucket names with "." do not work

### ISSUE THREAD

**Issue by pierre-b** [KnpLabs/KnpGaufretteBundle#48]
Hi guys,

When I set a bucket name wich contains a dot (example.com) I get an error "Could not write the xxxx content".

It works with bucket names wich do not contain dots.

Unfortunately to configure a bucket for Cloudfront, it requires a domain-like bucket name.

Here is my config:

``` yml
knp_gaufrette:
    adapters:
        uploads:
            amazon_s3:
                amazon_s3_id: service.amazon.s3
                bucket_name: example.com
                options:
                    create: true
    filesystems:
        amazon_s3:
            adapter: uploads
```
