### ISSUE TITLE
Ssh\Sftp not found

### ISSUE THREAD

**Issue by aMarcireau** [KnpLabs/KnpGaufretteBundle#74]
Hi,

I'm using the KnpGaufretteBundle with oneup uploader (https://github.com/1up-lab/OneupUploaderBundle) to store uploaded files in a distant folder.
## Problem

When I try to upload files from my browser, the server throws an error 500: 

```
title="Symfony\Component\Debug\Exception\FatalErrorException">FatalErrorException</abbr>: Error: Class 'Ssh\Sftp' not found in /Users/Alex/NXWebsite/app/cache/dev/appDevDebugProjectContainer.php line 1957</h2>
```
## Configuration 
- Symfony 2.3
- Composer.json (I installed the bundle using php composr.phar update):

``` JSON
"require": {
    "oneup/uploader-bundle": "1.0.*@dev",
    "knplabs/knp-gaufrette-bundle": "0.1.*"
}
```
- Parameters.yml:

``` yml
ssh_host:          127.0.0.1
ssh_username:      myUsername
ssh_password:      myPassword
ssh_path:          /my/path
```
- Configuration.yml:

``` yml
# One Up (video upload)
oneup_uploader:
    mappings:
        videos:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.videos_filesystem

# KNP gaufrette (storage layer)
knp_gaufrette:
    adapters:
        videos:
            sftp:
                sftp_id: nx_administration.sftp
                directory: %ssh_path%
                create: true
    filesystems:
        videos:
            adapter: videos
```
- nx_administration Bundle - Services.xml:

``` xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="nx_administration.ssh.configuration" class="Ssh\Configuration">
            <argument>%ssh_host%</argument>
        </service>
        <service id="nx_administration.ssh.authentication" class="Ssh\Authentication\Password">
            <argument>%ssh_username%</argument>
            <argument>%ssh_password%</argument>
        </service>
        <service id="nx_administration.ssh.session" class="Ssh\Session">
            <argument type="service" id="nx_administration.ssh.configuration"/>
            <argument type="service" id="nx_administration.ssh.authentication"/>
        </service>
        <service id="nx_administration.sftp" class="Ssh\Sftp">
            <argument type="service" id="nx_administration.ssh.session"/>
        </service>
    </services>
</container>
```
