### ISSUE TITLE
Stream Wrapper with aws_s3 adapter, does it work?

### ISSUE THREAD

**Issue by rayrigam** [KnpLabs/KnpGaufretteBundle#81]
I'm trying to use the stream wrapper to save uploaded images to AWS S3, using the following in my php upload code:

``` php
//... get and process $uploadedImage from Request
$destinationPath = 'gaufrette://my_assets/images/1.jpeg'
$f = fopen($destinationPath, 'w');
fwrite($f, $uploadedImage); 
fclose($f);
```

I first tried the following configuration using a "local" adapter as follows and it works (I'm able to save the new image to the local filesystem):

``` yaml
knp_gaufrette:
    adapters:
        my_assets:
            local:
                directory: "%kernel.root_dir%/../web"
    filesystems:
        my_assets:
            adapter:    my_assets
            alias:      my_assets_filesystem
    stream_wrapper: ~
```

However, when I try to use the aws_s3 adapter as follows, I get an unknown error:

``` yaml
knp_gaufrette:
    adapters:
        my_assets:
            aws_s3:
                service_id: acme.aws_s3.client
                bucket_name: %amazon_s3_bucket%
    filesystems:
        my_assets:
            adapter:    my_assets
            alias:      my_assets_filesystem
    stream_wrapper: ~

services:
    acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                key: %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%
```

Does the Amazon AWS S3 stream work by default with this bundle? or one needs to add or register some other class for the AWS S3 stream wrapper to work?
Could someone give further instructions about this?
