### ISSUE TITLE
There is no 'bar' filesystem defined

### ISSUE THREAD

**Issue by zeitnot** [KnpLabs/KnpGaufretteBundle#83]
My configuration is like that:

``` yml
knp_gaufrette:
    adapters:
        local_adapter:         
            local:
                directory: %kernel.root_dir%/../web/uploads        

    filesystems:
        bar:
            adapter:    local_adapter
            alias:      local_filesystem                    

```

When I am going to run <code>$ php app/console gaufrette:filesystem:keys bar
</code> from command line there is occuring an exception saying 
<code>
[RuntimeException]  
  There is no 'bar' filesystem defined.
</code>

Where did I make wrong? What is the correct way of installing this bundle?
