### ISSUE TITLE
Please add clear documentation for s3 regions

### ISSUE THREAD

**Issue by codecowboy** [KnpLabs/KnpGaufretteBundle#88]
I had hours of pain getting the S3 adapter talking to the eu-west-1 region.

Please add detailed instructions for setting regions in the documentation.

http://stackoverflow.com/questions/23307332/error-when-attempting-upload-to-s3-with-gaufrette/23307443#23307443

**Comment by sc0rp10** [comment]
+1
Also, there is an error with credentials:
```
services:
    acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%
```
Isn't correct; correct config looks like:
```
services:
    acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                credentials: # <-----
                    key: %amazon_s3.key%
                    secret: %amazon_s3.secret%
```
at https://github.com/KnpLabs/KnpGaufretteBundle#defining-services-1
